name: Tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version:
          - '3.13'
    name: Windows, SQLite, Python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'tests/requirements/py3.txt'
      - name: Install and upgrade packaging tools
        run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install -r tests/requirements/py3.txt -e .
      - name: Run tests
        working-directory: ./tests/
        run: python -Wall runtests.py -v2 --testrunner=junit_runner.JUnitXMLTestRunner --junit-output-dir=test-results
        env:
          JUNIT_OUTPUT_DIR: test-results
      - name: Merge JUnit XML files
        if: always()
        run: python scripts/merge_junit_xml.py tests/test-results tests/merged-junit-results.xml
      - name: Upload to Mergify CI Insights
        if: always()
        uses: mergifyio/gha-mergify-ci@v8
        with:
          token: ${{ secrets.MERGIFY_TOKEN }}
          job_name: Windows, SQLite, Python ${{ matrix.python-version }}
          report_path: tests/merged-junit-results.xml

  javascript-tests:
    runs-on: ubuntu-latest
    name: JavaScript tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package.json'
      - run: npm install
      - run: npm test
